[package]
name = "serde_rich"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true, features = ["derive"] }
rich = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true, features = ["std"] }
rich_derive = { workspace = true }
