[package]
name = "rich"
version = "0.1.0"
edition = {workspace = true}
repository = {workspace = true}
license = {workspace = true}
description = "generic framework to attach metadata to Rust values"

[dependencies]
